### ISSUE TITLE
How to create checkout from server

### ISSUE THREAD

**Issue by ashutoshgohil** [shardullavekar/midtransAndroid#1]
Hi,

I  am using your sample code, it is working fine with your credentials, now I want to test it from my server, please guide me how to do it from server side coding.

Thanks
Ash

**Comment by shardullavekar** [comment]
Hi, if you are using PHP on the backend, you can use Devsupport AI app at https://github.com/artpar/devsupport/releases/tag/v0.0.51 to complete your integration. 

If not, please refer to https://snap-docs.midtrans.com/#backend-integration

**Comment by ashutoshgohil** [comment]
Hi,
Can you please provide Backend sample then it would be easy for my developer.

**Comment by shardullavekar** [comment]
What's your back end technology? (PHP, Java, Go?)

**Comment by ashutoshgohil** [comment]
PHP

**Comment by shardullavekar** [comment]
Request you to please use the tool - it will give you readymade code snippet in PHP.

https://github.com/artpar/devsupport/releases/tag/v0.0.51

**Comment by ashutoshgohil** [comment]
Thanks, for providing link, I have checked but it is not clear which code I should use in PHP and upload code on PHP server, can you please help.

**Comment by shardullavekar** [comment]
Can you please help me with your Skype Id - will help you out.

**Comment by ashutoshgohil** [comment]
My skype id is:  mobiloitte_531, Please send request
